[env]
PROBE_RS_CHIP = "STM32F103RC"

PROBE_RS_SPEED    = "10000" # in kHz
PROBE_RS_PROTOCOL = "swd"   # swd or jtag

# LOG: trace, debug, info, warn, error
DEFMT_LOG              = "trace"
DEFMT_RTT_BUFFER_SIZE  = "1024"
CARGO_REGISTRY_DEFAULT = "rsproxy"

EMBASSY_EXECUTOR_TASK_ARENA_SIZE = "8192"


[alias]
rr = "r -r"
br = "b -r"
x  = "rr --"


[build]
target = "thumbv7m-none-eabi"
rustflags = [
    "-Clinker-plugin-lto",
    "-Clink-arg=--nmagic",
    "-Clink-arg=-Tlink.x",
    "-Clink-arg=-Tdefmt.x",
    # "-Cforce-frame-pointers",
    # "-Zmacro-backtrace",
]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# linker = "rust-lld"
runner = [
    "probe-rs",
    # `attach` or `run`
    "run",
    "--preverify",
    "--no-location",
    "--no-catch-reset",
    "--no-catch-hardfault",
    "--always-print-stacktrace",
    # "--rtt-scan-memory",
    # "--connect-under-reset",
    # "--log-format", "{L} {s}",
]
